#!/usr/bin/env node
/* Embeds plugin/*.lua into assets/plugin-files.js.
 *
 * The page ships the plugin source as a string so bundle generation costs zero
 * network requests. That creates a second copy, and a second copy that can
 * drift is exactly the bug acceptance criterion 3 exists to catch — so this
 * script is also the checker: `--check` fails when the embedded copy and
 * plugin/*.lua disagree, and verify-bundle.sh runs it that way.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCES = ["_meta.lua", "main.lua"];
const target = join(root, "assets", "plugin-files.js");

const files = {};
for (const name of SOURCES) {
    files[name] = readFileSync(join(root, "plugin", name), "utf8");
}

const body = SOURCES.map((n) => `    ${JSON.stringify(n)}: ${JSON.stringify(files[n])}`).join(",\n");
const out = `/* GENERATED by scripts/embed-plugin.mjs from plugin/*.lua. Do not edit.
 * Byte-identical to the files in plugin/; verify-bundle.sh enforces it. */
var KoboPluginFiles = {
${body}
};

if (typeof module !== "undefined" && module.exports) module.exports = KoboPluginFiles;
`;

if (process.argv.includes("--check")) {
    let current = "";
    try {
        current = readFileSync(target, "utf8");
    } catch {
        console.error("embed-plugin: assets/plugin-files.js is missing. Run: node scripts/embed-plugin.mjs");
        process.exit(1);
    }
    if (current !== out) {
        console.error("embed-plugin: assets/plugin-files.js is stale. Run: node scripts/embed-plugin.mjs");
        process.exit(1);
    }
    console.log("embed-plugin: embedded plugin sources match plugin/*.lua");
} else {
    writeFileSync(target, out);
    console.log(`embed-plugin: wrote ${target} (${out.length} bytes)`);
}
